---
author: "andrewjdyck"
date: "2017-03-11"
draft: false
title: "A Review of Open Data in Saskatachewan 2017"
slug: "/open-data-day-recap-2017"
tags: ["open-data-day","review"]
comments: true     # set false to hide Disqus comments
share: true        # set false to share buttons
menu: ""           # set "main" to add this content to the main menu
---
  

It was International Open Data Day on March 5, 2017. The day has breezed by me this year, as with many previous years. Let's review where the province has been on open data over this time and where it might be going.

### Recap of Open Data Saskatchewan
This site has now been live for just over 5 years. There hasn't been much change to the site over this time, but there have been some changes in the province. Now is as good a time as any to review some of these.

My initial thoughts for Open Data Saskatchewan was for it to be a thriving community of people across the province both using and promoting open data. I'd say that the open data movement in SK has been one with several fits and starts, but that whatever open data community there is, it would be a stretch to call it thriving. Rather, there are a handfull of people, perhaps a few dozen, spread across the province slowly making changes. 

My own progress on Open Data Saskatchewan has been slow as well, with several periods where I've attempted to re-imagine what this thing might be and what it might not be. I've settled for now and staying low-key and continuing to act as an unofficial resource for where to find open data in the province through scanning of the various ministries, municipalities and crown corporations. 

### Saskatchewan Open Data portals
The last 5 years have seen a great deal of progress for the creation of data portals. Indeed, the most difficult step in any project is to go from nothing to something, and that is what's happened in Saskatchewan in a pretty big way. 

#### City of Regina
This March marks a major revamp of the [City of Regina Open Data Portal](http://open.regina.ca/), now with more than 200 open datasets. When this site began, the number of open datasets available from Regina was zero and when the City first opened its portal, there were a small number of, arguably quite useful, datasets for download. 

#### City of Saskatoon
The [City of Saskatoon setup its data portal](http://opendata-saskatoon.cloudapp.net/) shortly after the City of Regina made the leap, first choosing a limited beta release for developers only and later opening this to the wider public. Like Regina, Saskatoon chose to get involved with [Microsoft's Open Government Data Initiative](https://news.microsoft.com/2009/05/07/microsoft-open-government-data-initiative-to-help-foster-transparency-and-collaboration/) (OGDI), which like many Microsoft initiatives, seems to have had a lot of energy poured into it in the beginning and [petered out](https://github.com/openlab/OGDI-DataLab) when it wasn't an instant success. Regina has stopped using the OGDI cloud solution, while Sasktaoon continues to use this as its open data portal host. I'd classify the datasets available through the City of Saskatoon as useful and valuable to developers, but there has been slower expansion of data available than Regina.

### Provincial open data
#### Battle of the prairies
Saskatchewan is among [just two provinces](http://open.canada.ca/en/maps/open-data-canada#overlay_0) to have avoided making the move towards government transparency via open data. One might think that competing to not be the last province in Canada to adopt an open data strategy would put a fire under both Saskatchewan and Manitoba, but both entities have held out so far. It will be an interesting race to see which of these provinces can leave the other with the title of the last province in Canada to adopt open data.

#### Requiem for dream of open GIS in Saskatchewan
There was once a pretty decent resource for geographical data in Saskatchewan. This was known as GeoSask - a partnership between the Government of Saskatchewan and one of it's crown corporations [Information Services Corporation](https://www.isc.ca/Pages/default.aspx) (ISC). GeoSask was a fantastic resource for data nerds and beyond with several geographical datasets relating to Saskatchewan available for use and exploration.

With little fanfare, the partnership between ISC and the government ended and on May 19, 2016, [GeoSask was shut down](https://www.isc.ca/Pages/Content%20Gallery/GeoSask.aspx). Some of the datasets available through GeoSask are still available in other locations, while others are not. The story of ISC and open data is a complex one that deserves a post of its own.

### What's next for open data in the province?
#### Provincial open data: steady as she goes
With the history of slow movement towards open data in Saskatchewan, I'd expect the trend to continue. I'd honestly put coin flip probability on whether Saskatchewan or Manitoba will be the last to make the move. I did see that the SK goverment posted (and presumably hired) a job with open data in the title a year or two back, so there must be some discussion about this topic in the halls of the public service.

#### Municipal open data: changes expected
With the recent update to the Regina open data portal, I do continue to see investment, both financial and strategic in transparency and connectivity. It wouldn't shock me to see the City of Saskatoon counter Regina's recent move and expand its portfolio of open datasets. Most likely I see this coming as they abandon the OGDI platform for something like CKAN.

#### Saskatchewan open data community
The open data community in Saskatchewan reflects its general population - small and diffuse. In theory, advances in connectivity (social media, social coding, etc.) should speed the development of communities in SK, but this has yet to be seen on a significant scale. During 2011, 2012, & 2013, there was some community momentum and while this momentum has slowed, I believe there is appetite for renewed activity if the right people get involved.
