---
author: "andrewjdyck"
date: "2020-10-20"
draft: true
title: "Open data letter to political parties - SK General Election 2020"
slug: "/open-data-positions-SK-GE-2020"
tags: ["election","democracy"]
comments: true     # set false to hide Disqus comments
share: true        # set false to share buttons
menu: ""           # set "main" to add this content to the main menu
---


# Letter to political parties

Sent to all six registered political parties in Saskatchewan on September 20, 2020.

> Hi,
>
> I write to you today to inquire about the *PARTY NAME HERE* position on a topic of importance to citizens of Saskatchewan. Information is foundational to both the full functioning of our democracy, as well as, increasingly, the successful integration of the information economy into that of our own.
>
> Open data, that is, the idea that some data, particularly data that is collected by government, should be freely available to everyone to use and republish as they wish, without restrictions from copyright, patents or other mechanisms of control. Some of the benefits of open data are copied at the end of this letter for your reference.
>
> I ask for your response on the *PARTY NAME HERE* position on open data as well as initiatives that the party is planning to take action on to deepen the culture of open data in Saskatchewan should your party form government in this year's election.
>
> Please note that I will be publishing this note, as well as your response on my website for others to view and potentially influence their voting decisions.
>
> Best, Andrew Dyck
>
> Principal, Open Data Saskatchewan
>
> <http://opendatask.ca>
>
> Benefits of open data: Support for innovation - Access to knowledge resources in the form of data supports innovation in the private sector by reducing duplication and promoting reuse of existing resources. The availability of data in machine-readable form allows for creative mash-ups that can be used to analyze markets, predict trends and requirements, and direct businesses in their strategic investment decisions.
>
> Advancing the government's accountability and democratic reform -- increased access to government data and information provides the public with greater insight into government activities, service delivery, and use of tax dollars.
>
> Leveraging public sector information to develop consumer and commercial products - Open and unrestricted access to scientific data for public interest purposes, particularly statistical, scientific, geographical, and environmental information, maximizes its use and value, and the reuse of existing data in commercial applications improves time-to-market for businesses.
>
> Better use of existing investment in broadband and community information infrastructure - Canada has invested in information and communications networks in the form of technical infrastructure and community services, such as libraries and social service agencies. This investment will continue to add value-for-money for Canadians by extending Web technology from one-way communications medium to collaborative environment.
>
> Support for research - Access to federal research data supports evidence-based primary research in Canadian and international academic, public sector, and industry-based research communities. Access to collections of data, reports, publications, and artifacts held in federal institutions allows for the use of these collections by researchers.
>
> Support informed decisions for consumers - Providing access to public sector service information to support informed decision-making; for example, real-time air travel statistics can help travelers to choose an airline and understand the factors that can lead to flight delays. Giving Canadians their say in decisions that affect them and the resulting potential for innovation and value (builds trust and credibility)
>
> Proactive Disclosure -- proactively providing data that is relevant to Canadians reduces the amount of access to information requests, e-mail campaigns and media inquiries. This greatly reduces the administrative cost and burden associated with responding to such inquiries.

# Responses

## Saskatchewan Party

October 9, 2020:

> Hello Andrew,
>
> A re-elected Saskatchewan Party Government would remain committed to accountable and transparent governance, robust record keeping, public access to information and maintaining the balance between privacy and strong public safety.
>
> The Saskatchewan Party believes it is important to find the appropriate balance between providing access to information and protecting the privacy of the residents of Saskatchewan. The public currently has access to information through the Legislative Assembly website, Publications Saskatchewan, Ehealth, Saskatchewan Gazette, Stats Can and additional online resources for each Ministry, Crown Corporation and independent officer.  
>
> In order to protect the privacy and information of the residents of Saskatchewan, a Saskatchewan Party government would need to undertake extensive legal and privacy review before providing access to additional types of information. 
>
> Thank you for taking the time to write in to us.
>
> Have a great day,
>
> [Name redacted]
>
> Research Team
>
> 2020 Saskatchewan Party Campaign

## New Democratic Party

October 14, 2020

> Good afternoon,
>
> I am happy to provide the following message on behalf of Saskatchewan's New Democrats regarding our position on open data issues.
>
> Please let me know if you have any additional questions or comments on the matter.
>
> I appreciate the opportunity to share our position on access to information and the steps that need to be taken to make data more freely available in the province. Saskatchewan New Democrats believe a provincial government should provide reasonable access to government data and information, so the public has the ability to make informed choices related to government services and spending without needing to go through the complicated freedom of information process.
>
> Last week, Saskatchewan New Democrats rolled out our plan to return to open and transparent governance if elected. This includes an accountability framework that includes expanded fiscal reporting and publication of government materials. In addition to these measures, we are committed to changing legislation so Saskatchewan's Information and Privacy Commissioner has the ability to compel the release of documents he or she determines should be released through The Freedom of Information and Protection of Privacy Act.
>
> I want to thank you for the opportunity to provide input on our party's position on open data. Please also accept my best wishes for your health and safety during the challenging times our province is facing with COVID-19.
>
> Thanks,
>
> [Names redacted]
>
> **Director of Research and Policy\
> **Saskatchewan New Democrats

## Regina Lakeview Candidates

### Megan Patterson

October 18, 2020:

> Hi Andrew!
>
> Sorry about my delay in responding!
>
> \
> Personally I believe data coupled with technology holds a great potential for our future. I believe that data is incredibly important - open GPS data for example has been a huge benefit for people and society - and open data can be used to help make policy decisions. Of course with data, particularly government data, we have to make sure individual personal information is protected. Moving health records online with EHealth records is big help to healthcare providers and patients and makes it much easier for both to access and review information, however we must ensure that someone's personal health records are never released or shared. \
> That being said, the potential for open data to help solve problems big and small is almost limitless; I recall reading a news item about a town in England using open data and the "hive mind" of local people to help fix a long-standing traffic problem they were having that was cheaper and easier than the previous "fixes" suggested by engineers and bureaucrats. The Saskatchewan Party government has shown a willingness to embrace innovation in the delivery of programs and services in the past, as well as recognizing the need to attract new investment through policies like the graduate retention program, the Saskatchewan Advantage Innovation Fund and Innovation Saskatchewan.\
> \
> I think a careful, measured approach to improve open source data is a good direction to go, with the potential to improve quality of life here in Saskatchewan, and I will be an advocate for it if elected on October 26th.\
> \
> Thank you for your question!\
> Enjoy the rest of your weekend!Kind regards,Megan

### Carla Beck

October 9, 2020:

> Hi Andrew,
>
> Are you able to provide your phone number? I would be very happy to speak to you about this further. 

\*This call has not taken place at the time of this writing, although, it's possible that the candidate called without leaving a message. I received a handful of calls from unlisted numbers in the week following the email exchange.
